#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d Browsing Development Design Music 

bspc config border_width          2
bspc config window_gap            30
bspc config focused_border_color  "#C678DD"
bspc config normal_border_color	  "ABB2BF"

bspc config top_padding		   43

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Fix Intellij
wmname LG3D &
bspc rule -a android-studio state=floating border=off follow=on

# Launch Polybar
$HOME/.config/polybar/launch.sh

# Set Background Image
~/.fehbg &

# Start Picom
picom -b --experimental-backends

